import { z } from "zod";
import { PROCESS_RESOURCE_ROLES } from "./processResourceTelemetry.js";

/** 诊断只接受固定技术分类；自由文本由业务层持有，不能进入日志/导出。 */
export const DiagnosticMetricSchema = z.enum([
  "durationMs",
  "startTimeUnixMs",
  "endTimeUnixMs",
  "cpuTimeMs",
  "count",
  "cpuPercent",
  "cpuPercentMean",
  "cpuPercentP95",
  "cpuPercentPeak",
  "rssBytes",
  "heapUsedBytes",
  "heapTotalBytes",
  "externalBytes",
  "rssKbMean",
  "rssKbPeak",
  "heapUsedKbMean",
  "heapUsedKbPeak",
  "userCpuMs",
  "systemCpuMs",
  "bytes",
  "peakBytes",
  "minMs",
  "maxMs",
  "meanMs",
  "p50Ms",
  "p95Ms",
  "p99Ms",
  "windowMs",
  "sampleCount",
  "successCount",
  "errorCount",
  "retryCount",
  "timeoutCount",
  "stallCount",
  "droppedCount",
  "activeCount",
  "processCount",
  "uptimeMs",
  "statusCode",
  "exitCode",
  "ttfbMs",
  "stageDurationMs",
  "queueMs",
  "firstTokenMs",
  "inputLagMs",
  "longTaskMs",
  "eventLoopDelayMs",
  "sequence",
  "rendererPrepareMs",
  "hostPrepareMs",
  "providerRegistrySyncMs",
  "taskMetaReadMs",
  "cliRequestMs",
  "cliBootstrapMs",
  "cliSessionRestoreMs",
  "initialFrameEncodeMs",
  "initialFrameTransportMs",
  "rendererSnapshotApplyMs",
  "reactRenderMs",
  "paintToInteractiveMs",
  "permissionWaitMs",
  "commandRunMs",
  "firstOutputMs",
  "noOutputMs",
  "outputBytes",
  "fsReadMs",
  "fsWriteMs",
  "patchMatchMs",
  "fileCount",
  "totalBytes",
  "maxFileBytes",
  "hunkCount",
  "matchAttempts",
  "toolCount",
  "failedToolCount",
  "modelRequestCount",
  "waitingMs",
  "retryDelayMs",
  "idleMs",
  "loafScriptCount",
  "loafTopDurationMs",
  "loafTopSharePercent",
  "attempt",
  "maxAttempts",
  "firstContentMs",
  "firstToolOutputMs",
  "inputTokens",
  "outputTokens",
  "hookCount",
  "hookRequestCount",
  "hookGrantedCount",
  "elapsedMs",
  "requestItemCount",
  "requestEnabledCount",
  "grantedRecordCount",
  "revokedCount",
  "generation",
  "sessionWorkspaceCount",
  "toolLayoutOpenCount",
  "syntaxTokenCacheCount",
  "syntaxHighlighterCount",
  "taskQueryCount",
  "taskMetaCount",
  "projectionStoreCount",
  "projectionRowCount",
  "terminalSessionCount",
  "taskSnapshotCount",
  "persistedTaskSnapshotCount",
  "sessionCount",
  "eventRowCount",
  "eventEvictedCount",
  "eventTransientRetainedCount",
  "publisherCount",
  "detachedLiveCount",
  "detachedTerminalCount",
  "rawSequenceStateCount",
  "arrayBuffersBytes",
  "sqliteCode",
  "migrationExecutedCount",
  "migrationCommittedCount",
  "dnsMs",
  "tcpMs",
  "tlsMs",
  "downloadMs",
  "taskBus.streamBatches",
  "taskBus.leases",
  "taskBus.sessionRoutes",
  "broadcast.claims",
  "broadcast.processes",
  "guest.tabs",
  "guest.closedTabIds",
  "app.windows",
  "app.willDownloadListeners",
  "fileWatcher.open",
  "terminal.open",
  "agent.sessionEmitters",
  "agent.seqStates",
  "agent.pendingPermissions",
  "agent.pendingUserInputs",
  "task.runtimeCommands",
  "task.toolMemoryTasks",
  "task.taskEmitters",
  "task.overlays",
  "ws.main",
  "ws.renderer_main",
  "ws.renderer_guest",
  "ws.gpu",
  "ws.chromium_other",
  "ws.host",
  "ws.scheduler",
  "ws.cli_chat",
  "ws.cli_aux",
  "ws.mcp",
]);
export const DiagnosticRecordSchema = z.strictObject({
  processRole: z.enum(PROCESS_RESOURCE_ROLES).optional(),
  version: z.literal(1).default(1),
  name: z.enum([
    "startup",
    "startup.database",
    "database_startup",
    "process.resource",
    "system.resource",
    "network.request",
    "process.crash",
    "process.unresponsive",
    "process_exit",
    "process_resource",
    "tool.resource",
    "tool_execution",
    "local.ttft",
    "ttft",
    "ui.action",
    "ui_latency",
    "stream_stall",
    "session_open",
    "error",
    "network",
    "model_request",
    "mcp_resource",
    "data_size",
    "long_task",
    "permission",
    "session",
    "runtime",
    "log",
  ]),
  component: z
    .enum(["main", "host", "scheduler", "renderer", "agent", "mcp", "tool", "server"])
    .optional(),
  status: z.enum(["ok", "error", "cancelled", "timeout", "unknown"]).optional(),
  phase: z.enum(["start", "end", "sample", "summary", "checkpoint"]).optional(),
  operation: z
    .enum([
      "goal_completion_verification",
      "goal_title_generation",
      "session_title_generation",
      "workspace_generate_text",
      "project_memory_extract",
    ])
    .optional(),
  stage: z
    .enum([
      "startup",
      "database",
      "prepare",
      "queue",
      "admission",
      "dispatch",
      "request",
      "response",
      "first_token",
      "first_frame",
      "render",
      "complete",
      "tool",
      "permission",
      "retry",
      "stall",
      "spawn",
      "connect",
      "handshake",
      "shutdown",
      "cold",
      "warm",
      "main",
      "host",
      "renderer",
      "agent",
      "bootstrap",
      "hydrate",
      "mount",
      "ready",
      "input",
      "stream",
      "provider_event",
      "content",
      "text",
      "renderer_prepare",
      "command_admission",
      "execution_wait",
      "request_prepare",
      "model_request",
      "output_return",
      "context",
      "hooks",
      "persistence",
      "compaction",
      "mcp",
      "tools",
      "request_assembly",
      "attempt",
      "retry_wait",
      "user_confirmation",
      "starting",
      "preparing_host_storage",
      "preparing_session_storage",
      "starting_services",
      "checking",
      "waiting_for_lock",
      "migrating",
      "committing",
      "maintaining",
      "failed",
    ])
    .optional(),
  transport: z.enum(["http", "rpc", "stdio", "websocket"]).optional(),
  errorCategory: z
    .enum([
      "auth",
      "permission",
      "timeout",
      "network",
      "protocol",
      "cancelled",
      "runtime",
      "quota",
      "overload",
      "storage",
      "unknown",
      "crash",
      "memory",
      "validation",
      "tool",
      "provider",
    ])
    .optional(),
  errorCode: z
    .enum([
      "EACCES",
      "EPERM",
      "ENOENT",
      "EEXIST",
      "ENOSPC",
      "ENOMEM",
      "EIO",
      "EPIPE",
      "EBUSY",
      "ECONNREFUSED",
      "ECONNRESET",
      "ETIMEDOUT",
      "ENOTFOUND",
      "EADDRINUSE",
      "ABORT_ERR",
      "ERR_OUT_OF_MEMORY",
      "ERR_NETWORK",
      "ERR_INVALID_ARG_TYPE",
    ])
    .optional(),
  // 只允许诊断创建者生成的随机 ID；不接受业务 identity、其散列或用户可控名称。
  traceId: z
    .string()
    .regex(/^(?!0{32}$)[0-9a-f]{32}$/)
    .optional(),
  spanId: z
    .string()
    .regex(/^(?!0{16}$)[0-9a-f]{16}$/)
    .optional(),
  parentSpanId: z
    .string()
    .regex(/^(?!0{16}$)[0-9a-f]{16}$/)
    .optional(),
  sequence: z.number().int().nonnegative().optional(),
  timestampUnixMs: z.number().int().min(0).max(18_446_744_073_709).optional(),
  metrics: z.partialRecord(DiagnosticMetricSchema, z.number().finite()).default({}),
});
export type DiagnosticRecord = z.infer<typeof DiagnosticRecordSchema>;
export type DiagnosticRecordInput = z.input<typeof DiagnosticRecordSchema>;

/** 跨进程和日志边界只接收数据属性，不执行 getter/toJSON，也不读取原型上的业务数据。 */
export function parseDiagnosticRecord(input: unknown): DiagnosticRecord | undefined {
  try {
    if (!input || typeof input !== "object" || Array.isArray(input)) return;
    const ownData = (value: object): Record<string, unknown> | undefined => {
      const entries = Object.entries(Object.getOwnPropertyDescriptors(value));
      if (entries.some(([, descriptor]) => !("value" in descriptor))) return;
      return Object.fromEntries(entries.map(([key, descriptor]) => [key, descriptor.value]));
    };
    const plain = ownData(input);
    if (!plain) return;
    if (plain.metrics !== undefined) {
      if (!plain.metrics || typeof plain.metrics !== "object" || Array.isArray(plain.metrics))
        return;
      plain.metrics = ownData(plain.metrics);
      if (!plain.metrics) return;
      plain.metrics = Object.fromEntries(
        Object.entries(plain.metrics as Record<string, unknown>).filter(
          ([key, value]) => value !== undefined || !DiagnosticMetricSchema.safeParse(key).success,
        ),
      );
    }
    const result = DiagnosticRecordSchema.safeParse(plain);
    return result.success ? result.data : undefined;
  } catch {
    return;
  }
}

export function createDiagnosticTraceId(): string {
  // HTTP 局域网 Web 的 randomUUID 不一定可用；getRandomValues 同样提供安全随机且无需安全上下文。
  return Array.from(globalThis.crypto.getRandomValues(new Uint8Array(16)), (byte) =>
    byte.toString(16).padStart(2, "0"),
  ).join("");
}
export function createDiagnosticSpanId(): string {
  return createDiagnosticTraceId().slice(0, 16);
}
